### ISSUE TITLE
Filter Ratio when Sample?

### ISSUE THREAD

**Issue by sunyasheng** [microsoft/VQ-Diffusion#1]
Terrific work! Great thanks for sharing your code! I am a little confused about the filter ratio [0.0, 0.5, 1.0] when you sample the image. I empirically find that 0.5 performs better. What does this paramter control? Did your paper mention it?

**Comment by cientgu** [comment]
It's a good question. Actually, the filter_ratio in models/dalle.py is not for sampling the image. It's for visualizing the image in the training procedure. 0.0 and 1.0 denote sampling image from x_t space (in other words, totally noisy distribution), and get a denoise image through 100 denoising steps. However, 0.5 denotes when given a clean image x0，go through 50 diffusion steps to add noise (50 = 100 * 0.5), and denoise the image by going through 50 steps. So it will get a better image. 
So it just helps to make sure the training works well. For testing or generating image, you need the function generate_content.

**Comment by sunyasheng** [comment]
Thank you for this super clear explanation. It really helps.

**Comment by miibotree** [comment]
I don't quite understand,  generate_content still calls the function sample or sample_fast. What's the parameter sample_type mean?
